// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp_DAL;

#nullable disable

namespace QuizAppDAL.Migrations
{
    [DbContext(typeof(EfDbContext))]
    partial class EfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizApp_DAL.Entities.Choice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10167de8-022b-4d8a-9828-17c4632b2391"),
                            QuestionId = new Guid("b9744d37-d7c6-43c5-81ab-b82b02e01aa3"),
                            Text = "System.out.println(\"Hello World\");"
                        },
                        new
                        {
                            Id = new Guid("6e72a0df-ec71-46a8-9ef7-87ab7c6b2261"),
                            QuestionId = new Guid("b9744d37-d7c6-43c5-81ab-b82b02e01aa3"),
                            Text = "cout << \"Hello World\""
                        },
                        new
                        {
                            Id = new Guid("b30e6130-73d6-4453-9524-428aabf3d1ff"),
                            QuestionId = new Guid("b9744d37-d7c6-43c5-81ab-b82b02e01aa3"),
                            Text = "Console.WriteLine(\"Hello World\")"
                        },
                        new
                        {
                            Id = new Guid("1f5f51e3-40b9-4d77-aa82-ce37f7841871"),
                            QuestionId = new Guid("749ac7fa-4687-4c0c-a2e4-974cba61a0e8"),
                            Text = "The & sign"
                        },
                        new
                        {
                            Id = new Guid("b803ce0e-1997-4b00-a589-8bf53d10d846"),
                            QuestionId = new Guid("749ac7fa-4687-4c0c-a2e4-974cba61a0e8"),
                            Text = "The * sign"
                        },
                        new
                        {
                            Id = new Guid("ef9a7cca-2a36-4029-a8d8-fbbe3f48a2f3"),
                            QuestionId = new Guid("749ac7fa-4687-4c0c-a2e4-974cba61a0e8"),
                            Text = "The + sign"
                        },
                        new
                        {
                            Id = new Guid("c6c67a58-dd8a-4fd7-85da-9f4efd67d7cf"),
                            QuestionId = new Guid("56891f72-811b-467b-a88e-d3f9be4b7081"),
                            Text = "/* This is a comment"
                        },
                        new
                        {
                            Id = new Guid("2d3b4929-6a1f-4145-8460-c5c2d58f3026"),
                            QuestionId = new Guid("56891f72-811b-467b-a88e-d3f9be4b7081"),
                            Text = "// This is a comment"
                        },
                        new
                        {
                            Id = new Guid("c20e9f32-3cc1-41da-8eda-700edc0e7a1e"),
                            QuestionId = new Guid("56891f72-811b-467b-a88e-d3f9be4b7081"),
                            Text = "# This is a comment"
                        },
                        new
                        {
                            Id = new Guid("29effdc0-ee24-4d23-b44c-daaae32b5a0b"),
                            QuestionId = new Guid("fb5f6c2d-8dd5-4281-91ce-f548ded2228e"),
                            Text = "myString"
                        },
                        new
                        {
                            Id = new Guid("8a2e6b18-f8dd-4401-92a3-e98f80926faf"),
                            QuestionId = new Guid("fb5f6c2d-8dd5-4281-91ce-f548ded2228e"),
                            Text = "Txt"
                        },
                        new
                        {
                            Id = new Guid("d58f8fd9-0d2f-44ce-a0f1-c302e0a1fb77"),
                            QuestionId = new Guid("fb5f6c2d-8dd5-4281-91ce-f548ded2228e"),
                            Text = "string"
                        },
                        new
                        {
                            Id = new Guid("9f9b48f9-61f9-4ec3-af43-4bb7a786c92d"),
                            QuestionId = new Guid("93fa1335-2bbd-4161-9f3c-824e22bd75e9"),
                            Text = "x = 5;"
                        },
                        new
                        {
                            Id = new Guid("34822d54-cd25-49c6-adb2-1483669e4199"),
                            QuestionId = new Guid("93fa1335-2bbd-4161-9f3c-824e22bd75e9"),
                            Text = "int x = 5;"
                        },
                        new
                        {
                            Id = new Guid("be3bb536-d5b6-407d-a93f-631e5a8dea2c"),
                            QuestionId = new Guid("93fa1335-2bbd-4161-9f3c-824e22bd75e9"),
                            Text = "num x = 5"
                        },
                        new
                        {
                            Id = new Guid("a3605028-62da-473f-a5e6-5dde9d101a92"),
                            QuestionId = new Guid("7c29852e-e182-459d-88a0-0634e1a093a2"),
                            Text = "Hyperlinks and Text Markup Language"
                        },
                        new
                        {
                            Id = new Guid("97419e21-ddf9-442c-9603-b99de96d8c35"),
                            QuestionId = new Guid("7c29852e-e182-459d-88a0-0634e1a093a2"),
                            Text = "Home Tool Markup Language"
                        },
                        new
                        {
                            Id = new Guid("7b5f1282-1620-44fc-967b-7efd1e04b232"),
                            QuestionId = new Guid("7c29852e-e182-459d-88a0-0634e1a093a2"),
                            Text = "Hyper Text Markup Language"
                        },
                        new
                        {
                            Id = new Guid("25769432-9fc5-4be8-b82f-3aa1b653bcc4"),
                            QuestionId = new Guid("cbbce265-2cbf-467f-a838-eddf6bcedd9f"),
                            Text = "The World Wide Web Consortium"
                        },
                        new
                        {
                            Id = new Guid("e836d58c-44be-4943-b526-8ed6e1d0449b"),
                            QuestionId = new Guid("cbbce265-2cbf-467f-a838-eddf6bcedd9f"),
                            Text = "Mozilla"
                        },
                        new
                        {
                            Id = new Guid("e825085f-09d1-45f5-8b65-b1b64da29a88"),
                            QuestionId = new Guid("cbbce265-2cbf-467f-a838-eddf6bcedd9f"),
                            Text = "Google"
                        },
                        new
                        {
                            Id = new Guid("7770b965-4695-4b19-b4ab-2c23168523b7"),
                            QuestionId = new Guid("a4ba9808-9beb-4152-9504-d0d1618a7307"),
                            Text = "<heading>"
                        },
                        new
                        {
                            Id = new Guid("1b6d7f63-9562-41da-ac00-b5284b1f5104"),
                            QuestionId = new Guid("a4ba9808-9beb-4152-9504-d0d1618a7307"),
                            Text = "<h1>"
                        },
                        new
                        {
                            Id = new Guid("dfc1af88-6627-43ac-9ca3-9a62078a6b73"),
                            QuestionId = new Guid("a4ba9808-9beb-4152-9504-d0d1618a7307"),
                            Text = "<head>"
                        },
                        new
                        {
                            Id = new Guid("ec646784-d6bd-4c27-9001-c84cb56f7a20"),
                            QuestionId = new Guid("1fc869a5-d338-4fcb-96ba-1db79cc0814c"),
                            Text = "<break>"
                        },
                        new
                        {
                            Id = new Guid("fe72f62d-a9f6-4251-b204-10d4243c414b"),
                            QuestionId = new Guid("1fc869a5-d338-4fcb-96ba-1db79cc0814c"),
                            Text = "<lb>"
                        },
                        new
                        {
                            Id = new Guid("e79a571d-4387-4c01-9acd-3adaf7a9ab8e"),
                            QuestionId = new Guid("1fc869a5-d338-4fcb-96ba-1db79cc0814c"),
                            Text = "<br>"
                        },
                        new
                        {
                            Id = new Guid("9e00556e-cbb5-4f0b-8ad4-52c1a74cb67b"),
                            QuestionId = new Guid("4fbd2b0c-9c48-4da7-b5dc-5dbce6b1d7b2"),
                            Text = "<em>"
                        },
                        new
                        {
                            Id = new Guid("d616ac6b-1aa3-4681-9c15-6e9ae87fc867"),
                            QuestionId = new Guid("4fbd2b0c-9c48-4da7-b5dc-5dbce6b1d7b2"),
                            Text = "<italic>"
                        },
                        new
                        {
                            Id = new Guid("6e504be4-e44d-4dd5-b321-21c894cf3a0c"),
                            QuestionId = new Guid("4fbd2b0c-9c48-4da7-b5dc-5dbce6b1d7b2"),
                            Text = "<i>"
                        },
                        new
                        {
                            Id = new Guid("b85bc922-1781-48b1-bc50-f777ad9aeb85"),
                            QuestionId = new Guid("109ea928-d48c-42d5-aeef-c70622f86f1c"),
                            Text = "Conceptual"
                        },
                        new
                        {
                            Id = new Guid("01ed4ddf-491f-4850-9781-1309938af31b"),
                            QuestionId = new Guid("109ea928-d48c-42d5-aeef-c70622f86f1c"),
                            Text = "Decision-making"
                        },
                        new
                        {
                            Id = new Guid("f9922860-dd0a-4019-b8e0-9ec0f46afaca"),
                            QuestionId = new Guid("109ea928-d48c-42d5-aeef-c70622f86f1c"),
                            Text = "Interpersonal"
                        },
                        new
                        {
                            Id = new Guid("2d31c648-d5b8-410b-b154-1670f06c0a14"),
                            QuestionId = new Guid("a9682130-8486-402c-a678-3b1fdae669a8"),
                            Text = "Technical skills"
                        },
                        new
                        {
                            Id = new Guid("645710ca-d812-4be3-9757-2a4f6e6866fa"),
                            QuestionId = new Guid("a9682130-8486-402c-a678-3b1fdae669a8"),
                            Text = "Time management skills"
                        },
                        new
                        {
                            Id = new Guid("f5ed2e32-ed03-400e-9761-9c6633c934fa"),
                            QuestionId = new Guid("a9682130-8486-402c-a678-3b1fdae669a8"),
                            Text = "Conceptual skills"
                        },
                        new
                        {
                            Id = new Guid("563288eb-baff-4d4a-a4bd-5e5c7b994307"),
                            QuestionId = new Guid("8d3d6d09-f092-419d-84f1-c39ffec5a2bf"),
                            Text = "Controlling"
                        },
                        new
                        {
                            Id = new Guid("ead20d3a-817d-4d45-adaa-2c859d5734a6"),
                            QuestionId = new Guid("8d3d6d09-f092-419d-84f1-c39ffec5a2bf"),
                            Text = "Organizing"
                        },
                        new
                        {
                            Id = new Guid("4412969c-053f-4625-9204-beffaabc0109"),
                            QuestionId = new Guid("8d3d6d09-f092-419d-84f1-c39ffec5a2bf"),
                            Text = "Leading"
                        },
                        new
                        {
                            Id = new Guid("40617427-0bc4-4209-9ff7-3d6a30f95570"),
                            QuestionId = new Guid("f390b872-dea2-4fe6-a1c9-2bed45d98830"),
                            Text = "Traceablity Matrix"
                        },
                        new
                        {
                            Id = new Guid("32249414-02a0-4168-aa71-3a0d1d8fb12e"),
                            QuestionId = new Guid("f390b872-dea2-4fe6-a1c9-2bed45d98830"),
                            Text = "Test Matrix"
                        },
                        new
                        {
                            Id = new Guid("970f6630-05c3-457c-a87c-2e861a337641"),
                            QuestionId = new Guid("f390b872-dea2-4fe6-a1c9-2bed45d98830"),
                            Text = "Checklist"
                        },
                        new
                        {
                            Id = new Guid("70a74497-01a5-4b2a-9d7f-d05f4775f0d9"),
                            QuestionId = new Guid("21d1a3ea-e936-4b56-8dd4-e82494122afc"),
                            Text = "Independent logic paths in the program"
                        },
                        new
                        {
                            Id = new Guid("f602b9e1-0a0e-4150-9865-d0133910ecac"),
                            QuestionId = new Guid("21d1a3ea-e936-4b56-8dd4-e82494122afc"),
                            Text = "Statements in the program"
                        },
                        new
                        {
                            Id = new Guid("e78c6e55-6a67-4a4f-a6cc-888de8c1de97"),
                            QuestionId = new Guid("21d1a3ea-e936-4b56-8dd4-e82494122afc"),
                            Text = "Cycles in the program"
                        },
                        new
                        {
                            Id = new Guid("a6480e73-91e5-4752-9deb-3a1fecb59379"),
                            QuestionId = new Guid("546e58f3-f8b8-4596-b74a-95c7dd27a346"),
                            Text = "A black box testing technique appropriate to all levels of testing"
                        },
                        new
                        {
                            Id = new Guid("3c308389-4fd9-402a-978e-b41cf875a10c"),
                            QuestionId = new Guid("546e58f3-f8b8-4596-b74a-95c7dd27a346"),
                            Text = "A white box testing technique appropriate for component testing"
                        },
                        new
                        {
                            Id = new Guid("2964bab6-6070-440f-b850-e9d922a2442d"),
                            QuestionId = new Guid("546e58f3-f8b8-4596-b74a-95c7dd27a346"),
                            Text = "A black box testing technique than can only be used during system testing"
                        },
                        new
                        {
                            Id = new Guid("6ab62c60-7db4-4cf5-8977-d701f8ac54a9"),
                            QuestionId = new Guid("38cf6409-c1de-4553-af07-d15bd6a019a5"),
                            Text = "HR practices"
                        },
                        new
                        {
                            Id = new Guid("fc0df8ce-3ce1-4d75-9f4a-bed6a06d36e6"),
                            QuestionId = new Guid("38cf6409-c1de-4553-af07-d15bd6a019a5"),
                            Text = "HR department"
                        },
                        new
                        {
                            Id = new Guid("65b56702-b549-4165-bf70-88c51290a081"),
                            QuestionId = new Guid("38cf6409-c1de-4553-af07-d15bd6a019a5"),
                            Text = "HR tools"
                        },
                        new
                        {
                            Id = new Guid("59b9a61f-6927-4619-b98e-3c2435e1344b"),
                            QuestionId = new Guid("82850071-298d-4155-9342-a30769b2cc8a"),
                            Text = "Managing Employee Competencies"
                        },
                        new
                        {
                            Id = new Guid("75716c14-8663-4af3-92d6-c83148b1680a"),
                            QuestionId = new Guid("82850071-298d-4155-9342-a30769b2cc8a"),
                            Text = "Managing Employee Attitudes and Behaviors"
                        },
                        new
                        {
                            Id = new Guid("6ace3361-fed0-4784-a01e-e9ac083f6bd2"),
                            QuestionId = new Guid("82850071-298d-4155-9342-a30769b2cc8a"),
                            Text = "Compensation and incentives"
                        },
                        new
                        {
                            Id = new Guid("41a7fae1-7e84-4b8a-a1cb-dd4007fd5e0b"),
                            QuestionId = new Guid("839f2a81-5566-400e-8af9-df42d221df5c"),
                            Text = "Health care"
                        },
                        new
                        {
                            Id = new Guid("28cbc296-8184-447a-ab69-5f2821165a78"),
                            QuestionId = new Guid("839f2a81-5566-400e-8af9-df42d221df5c"),
                            Text = "Social Security"
                        },
                        new
                        {
                            Id = new Guid("4fc92837-8131-4fe0-ba53-e8f96b1fc41a"),
                            QuestionId = new Guid("839f2a81-5566-400e-8af9-df42d221df5c"),
                            Text = "Compliance with OSHA"
                        },
                        new
                        {
                            Id = new Guid("d4048da5-7848-4da7-9c84-48094b888c96"),
                            QuestionId = new Guid("7a5593dc-a11f-458c-98d3-2ec8b5476c8b"),
                            Text = "Mutual Fund"
                        },
                        new
                        {
                            Id = new Guid("3309d1b1-c234-48cf-bad5-f40b983a3df2"),
                            QuestionId = new Guid("7a5593dc-a11f-458c-98d3-2ec8b5476c8b"),
                            Text = "RRSP"
                        },
                        new
                        {
                            Id = new Guid("259c1073-6276-4a52-a3b5-8333d743654f"),
                            QuestionId = new Guid("7a5593dc-a11f-458c-98d3-2ec8b5476c8b"),
                            Text = "ETF"
                        },
                        new
                        {
                            Id = new Guid("43eed3a4-b55a-4189-a08d-59d56f5d49a4"),
                            QuestionId = new Guid("489eddce-71ee-4cc2-9d0e-555a0582431f"),
                            Text = "It's easier to invest too much too fast"
                        },
                        new
                        {
                            Id = new Guid("03ababf4-bb09-493c-8e7f-99c19d4c90bd"),
                            QuestionId = new Guid("489eddce-71ee-4cc2-9d0e-555a0582431f"),
                            Text = "One can monitor investments in real time"
                        },
                        new
                        {
                            Id = new Guid("50068619-b8cf-4a50-ba76-df21f03c90f1"),
                            QuestionId = new Guid("489eddce-71ee-4cc2-9d0e-555a0582431f"),
                            Text = "Online accessibility"
                        },
                        new
                        {
                            Id = new Guid("93c828b1-3065-419c-94ee-3009b0086a5f"),
                            QuestionId = new Guid("d134ce37-f871-4be3-aa47-ed363abddc96"),
                            Text = "Bond"
                        },
                        new
                        {
                            Id = new Guid("2be15a5f-fc23-4a3c-a9ea-e54f5f270e93"),
                            QuestionId = new Guid("d134ce37-f871-4be3-aa47-ed363abddc96"),
                            Text = "REIT"
                        },
                        new
                        {
                            Id = new Guid("046f194f-933a-4b43-a48a-d81264f8f6a8"),
                            QuestionId = new Guid("d134ce37-f871-4be3-aa47-ed363abddc96"),
                            Text = "Equity"
                        });
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9744d37-d7c6-43c5-81ab-b82b02e01aa3"),
                            CorrectAnswer = "Console.WriteLine(\"Hello World\")",
                            QuestionText = "What is a correct syntax to output 'Hello World' in C#?",
                            QuizId = new Guid("5491d598-3798-4c4f-a99f-f021e1406797")
                        },
                        new
                        {
                            Id = new Guid("749ac7fa-4687-4c0c-a2e4-974cba61a0e8"),
                            CorrectAnswer = "The + sign",
                            QuestionText = "Which operator is used to add together two values?",
                            QuizId = new Guid("5491d598-3798-4c4f-a99f-f021e1406797")
                        },
                        new
                        {
                            Id = new Guid("56891f72-811b-467b-a88e-d3f9be4b7081"),
                            CorrectAnswer = "// This is a comment",
                            QuestionText = "How do you insert COMMENTS in C# code?",
                            QuizId = new Guid("5491d598-3798-4c4f-a99f-f021e1406797")
                        },
                        new
                        {
                            Id = new Guid("fb5f6c2d-8dd5-4281-91ce-f548ded2228e"),
                            CorrectAnswer = "string",
                            QuestionText = "Which data type is used to create a variable that should store text?",
                            QuizId = new Guid("5491d598-3798-4c4f-a99f-f021e1406797")
                        },
                        new
                        {
                            Id = new Guid("93fa1335-2bbd-4161-9f3c-824e22bd75e9"),
                            CorrectAnswer = "int x = 5;",
                            QuestionText = "How do you create a variable with the numeric value 5?",
                            QuizId = new Guid("5491d598-3798-4c4f-a99f-f021e1406797")
                        },
                        new
                        {
                            Id = new Guid("7c29852e-e182-459d-88a0-0634e1a093a2"),
                            CorrectAnswer = "Hyper Text Markup Language",
                            QuestionText = "What does HTML stand for?",
                            QuizId = new Guid("6e60e6cb-5f99-459d-9e89-96425b57462f")
                        },
                        new
                        {
                            Id = new Guid("cbbce265-2cbf-467f-a838-eddf6bcedd9f"),
                            CorrectAnswer = "The World Wide Web Consortium",
                            QuestionText = "Who is making the Web standards?",
                            QuizId = new Guid("6e60e6cb-5f99-459d-9e89-96425b57462f")
                        },
                        new
                        {
                            Id = new Guid("a4ba9808-9beb-4152-9504-d0d1618a7307"),
                            CorrectAnswer = "<h1>",
                            QuestionText = "Choose the correct HTML element for the largest heading:",
                            QuizId = new Guid("6e60e6cb-5f99-459d-9e89-96425b57462f")
                        },
                        new
                        {
                            Id = new Guid("1fc869a5-d338-4fcb-96ba-1db79cc0814c"),
                            CorrectAnswer = "<br>",
                            QuestionText = "What is the correct HTML element for inserting a line break?",
                            QuizId = new Guid("6e60e6cb-5f99-459d-9e89-96425b57462f")
                        },
                        new
                        {
                            Id = new Guid("4fbd2b0c-9c48-4da7-b5dc-5dbce6b1d7b2"),
                            CorrectAnswer = "<em>",
                            QuestionText = "Choose the correct HTML element to define emphasized text",
                            QuizId = new Guid("6e60e6cb-5f99-459d-9e89-96425b57462f")
                        },
                        new
                        {
                            Id = new Guid("109ea928-d48c-42d5-aeef-c70622f86f1c"),
                            CorrectAnswer = "Conceptual",
                            QuestionText = "What skills depend on the manager's ability to think in the abstract?",
                            QuizId = new Guid("44f8f00a-17e6-46d9-9e0c-be3326514c02")
                        },
                        new
                        {
                            Id = new Guid("a9682130-8486-402c-a678-3b1fdae669a8"),
                            CorrectAnswer = "Technical skills",
                            QuestionText = "The skills necessary to accomplish or understand the specific kind of work done in an organization are called what?",
                            QuizId = new Guid("44f8f00a-17e6-46d9-9e0c-be3326514c02")
                        },
                        new
                        {
                            Id = new Guid("8d3d6d09-f092-419d-84f1-c39ffec5a2bf"),
                            CorrectAnswer = "Controlling",
                            QuestionText = "Monitoring and correcting ongoing activities that facilitate goal attainment is defined as:",
                            QuizId = new Guid("44f8f00a-17e6-46d9-9e0c-be3326514c02")
                        },
                        new
                        {
                            Id = new Guid("f390b872-dea2-4fe6-a1c9-2bed45d98830"),
                            CorrectAnswer = "Traceablity Matrix",
                            QuestionText = "Executing the same test case by giving the number of inputs on same build called as",
                            QuizId = new Guid("43e0817d-8e88-41dd-bcfa-7ec05ef7f283")
                        },
                        new
                        {
                            Id = new Guid("21d1a3ea-e936-4b56-8dd4-e82494122afc"),
                            CorrectAnswer = "Independent logic paths in the program",
                            QuestionText = "The cyclomatic complexity metric provides the designer with information regarding the number of",
                            QuizId = new Guid("43e0817d-8e88-41dd-bcfa-7ec05ef7f283")
                        },
                        new
                        {
                            Id = new Guid("546e58f3-f8b8-4596-b74a-95c7dd27a346"),
                            CorrectAnswer = "A black box testing technique appropriate to all levels of testing",
                            QuestionText = "Equivalence partitioning is:",
                            QuizId = new Guid("43e0817d-8e88-41dd-bcfa-7ec05ef7f283")
                        },
                        new
                        {
                            Id = new Guid("38cf6409-c1de-4553-af07-d15bd6a019a5"),
                            CorrectAnswer = "HR practices",
                            QuestionText = "Tools a company uses to manage employees are?",
                            QuizId = new Guid("b1336dc5-1db4-4ec8-aa88-9d17c8d0267d")
                        },
                        new
                        {
                            Id = new Guid("82850071-298d-4155-9342-a30769b2cc8a"),
                            CorrectAnswer = "Managing Employee Competencies",
                            QuestionText = "Ensuring Employees have the necessary knowledge, skills, abilities, and other talents to achieve work objectives falls under which of the following categories?",
                            QuizId = new Guid("b1336dc5-1db4-4ec8-aa88-9d17c8d0267d")
                        },
                        new
                        {
                            Id = new Guid("839f2a81-5566-400e-8af9-df42d221df5c"),
                            CorrectAnswer = "Health care",
                            QuestionText = "Which of the following is not one of the benefits, health, and wellness required by law?",
                            QuizId = new Guid("b1336dc5-1db4-4ec8-aa88-9d17c8d0267d")
                        },
                        new
                        {
                            Id = new Guid("7a5593dc-a11f-458c-98d3-2ec8b5476c8b"),
                            CorrectAnswer = "Mutual Fund",
                            QuestionText = "Which of the following type of investment allows an individual to purchase into an entire industry, commodity group, or stock market?",
                            QuizId = new Guid("73b4acad-b234-40b5-aa20-35d4f071a89e")
                        },
                        new
                        {
                            Id = new Guid("489eddce-71ee-4cc2-9d0e-555a0582431f"),
                            CorrectAnswer = "It's easier to invest too much too fast",
                            QuestionText = "Which of the following is NOT a benefit of online trading?",
                            QuizId = new Guid("73b4acad-b234-40b5-aa20-35d4f071a89e")
                        },
                        new
                        {
                            Id = new Guid("d134ce37-f871-4be3-aa47-ed363abddc96"),
                            CorrectAnswer = "Bond",
                            QuestionText = "Increasing the percentage of which type of investment in your portfolio will lower your overall investment risk?",
                            QuizId = new Guid("73b4acad-b234-40b5-aa20-35d4f071a89e")
                        });
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5491d598-3798-4c4f-a99f-f021e1406797"),
                            Description = "The test contains 5 questions and there is no time limit. The test is not official,\r\n                           it's just a nice way to see how much you know, or don't know, about C#.",
                            Title = "C# Quiz"
                        },
                        new
                        {
                            Id = new Guid("6e60e6cb-5f99-459d-9e89-96425b57462f"),
                            Description = "The test contains 5 questions and there is no time limit. The test is not official,\r\n                           it's just a nice way to see how much you know, or don't know, about HTML.",
                            Title = "HTML Quiz"
                        },
                        new
                        {
                            Id = new Guid("44f8f00a-17e6-46d9-9e0c-be3326514c02"),
                            Description = "If you are in the management field and looking for a well-researched 'Introduction to Management' practice quiz with answers, you've reached the right place. Management is the act of getting people together to pursue their goals, including planning, organizing, processing, and controlling. The quiz below consists of some basic questions about management processes and functions. Do you think you can quickly answer all of them? Take up this quiz and prove your knowledge now.",
                            Title = "Management Quiz"
                        },
                        new
                        {
                            Id = new Guid("43e0817d-8e88-41dd-bcfa-7ec05ef7f283"),
                            Description = "Take a shot at this quiz, which will help you determine your IQ, your QA knowledge. Best luck.",
                            Title = "QA Quiz"
                        },
                        new
                        {
                            Id = new Guid("b1336dc5-1db4-4ec8-aa88-9d17c8d0267d"),
                            Description = "This is a quiz with HR test questions. The first one, made in a series of tests made to help me prepare for my human resource management exam. All material was taken from the Human Resource Management Book by David Lepak and Mary Gowan. Why don't you give it a try and let it do the same for you? All the best, and share it with your classmates!",
                            Title = "HR Quiz"
                        },
                        new
                        {
                            Id = new Guid("73b4acad-b234-40b5-aa20-35d4f071a89e"),
                            Description = "With the advancement of society and the internet, the investment world has changed dramatically. How well do you know about various investment strategies? If you know enough, then feel free to give this fun and informative quiz a try! Just answer a few questions to enter the world of stocks, online trading, bond, etc. Are you ready? There's no time bar, so feel free to take this quiz as often as possible! We hope you learn some new things with the quiz! Good Luck!",
                            Title = "Investment Quiz"
                        });
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6690193a-3dbc-416c-8a20-9751b4c48f57"),
                            Title = "User"
                        },
                        new
                        {
                            Id = new Guid("c86deec2-7efa-4c13-a4ea-7614c37945d2"),
                            Title = "Admin"
                        });
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRolesList");
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.Choice", b =>
                {
                    b.HasOne("QuizApp_DAL.Entities.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.Question", b =>
                {
                    b.HasOne("QuizApp_DAL.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.UserRoles", b =>
                {
                    b.HasOne("QuizApp_DAL.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizApp_DAL.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizApp_DAL.Entities.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
